type RecipeBase = {
  id: string;
  name: string;
  ingredients: string[];
  method: string[];
};

// Recipe sa parsed from AsyncStorage
type RecipeRaw = RecipeBase & {
  createdAt: string;
  modifiedAt: string;
};

type Recipe = RecipeBase & {
  createdAt: Date;
  modifiedAt: Date;
};

type RecipeUpdate = Omit<Recipe, 'createdAt'>;

const NEW_RECIPE_ID = 'NEW RECIPE';

const RECIPES: Recipe[] = [
  {
    id: 'a',
    name: 'Pasta e Fagioli',
    ingredients: [
      '2 cans cannellini beans',
      'several cloves garlic',
      'lots olive oil',
      'some canned tomato, maybe 1/4 cup',
      '1/2 box of ditalini',
    ],
    method: [
      'Saute garlic in oil.',
      'Puree 1/2 of the beans with the tomato.',
      'Add puree and rest of the whole beans to the pot.',
      'Simmer for 30 mins or so.',
      'Cook pasta al dente and add to the soup.',
    ],
    createdAt: new Date('2023-01-01T10:00:00Z'),
    modifiedAt: new Date('2023-01-02T12:00:00Z'),
  },
  {
    id: 'b',
    name: 'Pad Kee Mao',
    ingredients: [
      '8 oz wide rice noodles',
      '2 tbsp vegetable oil',
      '3 cloves garlic, minced',
      "1-2 bird's eye chilies, chopped",
      '1/4 cup oyster sauce',
      '2 tbsp soy sauce',
      '1 tbsp fish sauce',
      '1 tbsp sugar',
      '1/4 cup Thai basil leaves',
      '1/2 cup sliced bell peppers',
      '1/2 cup sliced onion',
    ],
    method: [
      'Soak rice noodles in warm water until soft, then drain.',
      'Heat oil in a wok over high heat.',
      'Add garlic and chilies, stir-fry for 30 seconds.',
      'Add onions and bell peppers, stir-fry until slightly softened.',
      'Add noodles and sauces (oyster, soy, fish, sugar), toss to coat evenly.',
      'Add Thai basil leaves, stir-fry until wilted.',
      'Serve hot.',
    ],
    createdAt: new Date('2023-02-01T09:00:00Z'),
    modifiedAt: new Date('2023-02-01T10:30:00Z'),
  },
  {
    id: 'c',
    name: "Penne all'Arrabbiata",
    ingredients: [
      '1 lb penne pasta',
      '3 tbsp olive oil',
      '4 cloves garlic, thinly sliced',
      '1/2 tsp red chili flakes (adjust to taste)',
      '1 can (14 oz) crushed tomatoes',
      'Salt to taste',
      'Fresh parsley, chopped (optional)',
      'Freshly grated Parmesan cheese (optional)',
    ],
    method: [
      'Cook penne in a large pot of salted boiling water until al dente, then drain.',
      'Heat olive oil in a skillet over medium heat.',
      'Add garlic and chili flakes, sauté until fragrant.',
      'Stir in crushed tomatoes, season with salt, and simmer for 15 minutes.',
      'Add cooked pasta to the sauce, toss to coat.',
      'Garnish with parsley and Parmesan, if desired.',
      'Serve immediately.',
    ],
    createdAt: new Date('2023-03-01T08:00:00Z'),
    modifiedAt: new Date('2023-03-02T08:30:00Z'),
  },
  {
    id: 'd',
    name: 'Classic Margherita Pizza',
    ingredients: [
      '1 ball pizza dough',
      '1/2 cup marinara sauce',
      '4 oz fresh mozzarella, sliced',
      '2-3 fresh basil leaves',
      '1 tbsp olive oil',
    ],
    method: [
      'Preheat oven to 475°F (245°C).',
      'Roll out pizza dough on a floured surface.',
      'Spread marinara sauce evenly over the dough.',
      'Top with fresh mozzarella slices.',
      'Bake for 10-12 minutes until crust is golden and cheese is bubbling.',
      'Remove from oven and top with fresh basil leaves and a drizzle of olive oil.',
      'Slice and serve hot.',
    ],
    createdAt: new Date('2023-04-01T07:00:00Z'),
    modifiedAt: new Date('2023-04-01T09:00:00Z'),
  },
  {
    id: 'e',
    name: 'Chicken Tikka Masala',
    ingredients: [
      '1 lb chicken thighs, cut into bite-sized pieces',
      '1 cup plain yogurt',
      '2 tbsp tikka masala spice mix',
      '2 tbsp vegetable oil',
      '1 large onion, finely chopped',
      '3 cloves garlic, minced',
      '1-inch piece ginger, grated',
      '1 can (14 oz) tomato puree',
      '1 cup heavy cream',
      'Salt to taste',
      'Fresh cilantro, chopped (for garnish)',
    ],
    method: [
      'Marinate chicken in yogurt and tikka masala spice mix for at least 1 hour.',
      'Heat oil in a skillet over medium heat.',
      'Cook marinated chicken until browned and cooked through, then set aside.',
      'In the same skillet, sauté onions, garlic, and ginger until softened.',
      'Add tomato puree and simmer for 10 minutes.',
      'Stir in heavy cream and cooked chicken, simmer for another 5 minutes.',
      'Season with salt and garnish with fresh cilantro before serving.',
    ],
    createdAt: new Date('2023-05-01T06:00:00Z'),
    modifiedAt: new Date('2023-05-01T07:30:00Z'),
  },
  {
    id: 'f',
    name: 'Shakshuka',
    ingredients: [
      '2 tbsp olive oil',
      '1 onion, finely chopped',
      '1 red bell pepper, diced',
      '3 cloves garlic, minced',
      '1 tsp ground cumin',
      '1 tsp smoked paprika',
      '1/4 tsp cayenne pepper',
      '1 can (14 oz) diced tomatoes',
      '4 large eggs',
      'Salt and pepper to taste',
      'Fresh parsley, chopped (for garnish)',
      'Crusty bread (for serving)',
    ],
    method: [
      'Heat olive oil in a skillet over medium heat.',
      'Sauté onion and bell pepper until softened.',
      'Add garlic, cumin, smoked paprika, and cayenne, cook for 1 minute.',
      'Stir in diced tomatoes, season with salt and pepper, and simmer for 10 minutes.',
      'Make small wells in the sauce and crack eggs into the wells.',
      'Cover and cook until egg whites are set but yolks are still runny.',
      'Garnish with parsley and serve with crusty bread.',
    ],
    createdAt: new Date('2023-06-01T05:00:00Z'),
    modifiedAt: new Date('2023-06-01T06:00:00Z'),
  },
  {
    id: 'g',
    name: 'Guacamole',
    ingredients: [
      '3 ripe avocados',
      '1 lime, juiced',
      '1/2 tsp salt',
      '1/2 cup diced red onion',
      '2 Roma tomatoes, diced',
      '1 jalapeño, seeded and finely chopped',
      '2 tbsp fresh cilantro, chopped',
    ],
    method: [
      'Mash avocados in a bowl.',
      'Stir in lime juice and salt.',
      'Mix in red onion, tomatoes, jalapeño, and cilantro.',
      'Taste and adjust seasoning as needed.',
      'Serve immediately with tortilla chips or as a topping.',
    ],
    createdAt: new Date('2023-07-01T04:00:00Z'),
    modifiedAt: new Date('2023-07-01T05:00:00Z'),
  },
  {
    id: 'h',
    name: 'Vegetable Stir-Fry',
    ingredients: [
      '2 tbsp vegetable oil',
      '1 red bell pepper, sliced',
      '1 yellow bell pepper, sliced',
      '1 zucchini, sliced',
      '1 cup broccoli florets',
      '2 cloves garlic, minced',
      '1 tbsp soy sauce',
      '1 tbsp oyster sauce',
      '1 tsp sesame oil',
      '1 tsp cornstarch mixed with 2 tbsp water (optional for thickening)',
    ],
    method: [
      'Heat vegetable oil in a large skillet or wok over high heat.',
      'Add garlic and stir-fry for 30 seconds until fragrant.',
      'Add bell peppers, zucchini, and broccoli, stir-fry for 3-5 minutes.',
      'Add soy sauce, oyster sauce, and sesame oil, tossing to coat the vegetables.',
      'If desired, add cornstarch slurry and cook for another 1-2 minutes until sauce thickens.',
      'Serve immediately over steamed rice or noodles.',
    ],
    createdAt: new Date('2023-08-01T03:00:00Z'),
    modifiedAt: new Date('2023-08-01T04:30:00Z'),
  },
  {
    id: 'i',
    name: 'Chocolate Chip Pancakes',
    ingredients: [
      '1 cup all-purpose flour',
      '2 tbsp sugar',
      '1 tsp baking powder',
      '1/2 tsp baking soda',
      '1/4 tsp salt',
      '1 cup buttermilk',
      '1 large egg',
      '2 tbsp melted butter',
      '1/2 cup chocolate chips',
      'Butter or oil for cooking',
      'Maple syrup (for serving)',
    ],
    method: [
      'In a large bowl, whisk together flour, sugar, baking powder, baking soda, and salt.',
      'In a separate bowl, whisk buttermilk, egg, and melted butter.',
      'Pour the wet ingredients into the dry ingredients and stir until just combined.',
      'Fold in chocolate chips.',
      'Heat a non-stick skillet over medium heat and grease lightly with butter or oil.',
      'Pour 1/4 cup batter onto the skillet and cook until bubbles form, about 2 minutes.',
      'Flip and cook the other side for 1-2 minutes until golden brown.',
      'Serve with maple syrup.',
    ],
    createdAt: new Date('2023-09-01T02:00:00Z'),
    modifiedAt: new Date('2023-09-01T03:00:00Z'),
  },
  {
    id: 'j',
    name: 'Classic Caprese Salad',
    ingredients: [
      '3 ripe tomatoes, sliced',
      '8 oz fresh mozzarella, sliced',
      '1/4 cup fresh basil leaves',
      '2 tbsp extra virgin olive oil',
      '1 tbsp balsamic vinegar',
      'Salt and freshly ground black pepper to taste',
    ],
    method: [
      'Arrange alternating slices of tomato and mozzarella on a plate.',
      'Tuck basil leaves between the slices.',
      'Drizzle with olive oil and balsamic vinegar.',
      'Season with salt and pepper.',
      'Serve immediately as a refreshing appetizer or side dish.',
    ],
    createdAt: new Date('2023-10-01T01:00:00Z'),
    modifiedAt: new Date('2023-10-01T02:00:00Z'),
  },
  {
    id: 'k',
    name: 'Garlic Butter Shrimp',
    ingredients: [
      '1 lb large shrimp, peeled and deveined',
      '2 tbsp olive oil',
      '3 cloves garlic, minced',
      '3 tbsp unsalted butter',
      '1/4 cup fresh parsley, chopped',
      'Juice of 1 lemon',
      'Salt and pepper to taste',
    ],
    method: [
      'Heat olive oil in a large skillet over medium heat.',
      'Add shrimp, season with salt and pepper, and cook for 2-3 minutes per side until pink and opaque.',
      'Remove shrimp from the skillet and set aside.',
      'In the same skillet, melt butter and sauté garlic until fragrant, about 1 minute.',
      'Stir in lemon juice and parsley.',
      'Return shrimp to the skillet and toss to coat in the garlic butter.',
      'Serve immediately with crusty bread or over rice.',
    ],
    createdAt: new Date('2023-11-01T00:00:00Z'),
    modifiedAt: new Date('2023-11-01T01:00:00Z'),
  },
  {
    id: 'l',
    name: 'Mango Lassi',
    ingredients: [
      '1 cup ripe mango chunks',
      '1/2 cup plain yogurt',
      '1/2 cup milk',
      '2 tbsp sugar (or to taste)',
      '1/4 tsp cardamom powder',
      'Ice cubes (optional)',
    ],
    method: [
      'Blend mango chunks, yogurt, milk, sugar, and cardamom powder in a blender until smooth.',
      'Add ice cubes if desired and blend again.',
      'Pour into glasses and serve chilled.',
    ],
    createdAt: new Date('2023-12-01T23:00:00Z'),
    modifiedAt: new Date('2023-12-02T00:00:00Z'),
  },
  {
    id: 'm',
    name: 'Baked Salmon with Dill',
    ingredients: [
      '4 salmon fillets',
      '2 tbsp olive oil',
      '1 lemon, sliced',
      '2 tbsp fresh dill, chopped',
      'Salt and pepper to taste',
    ],
    method: [
      'Preheat oven to 375°F (190°C).',
      'Place salmon fillets on a baking sheet lined with parchment paper.',
      'Drizzle with olive oil and season with salt and pepper.',
      'Top each fillet with a slice of lemon and sprinkle with dill.',
      'Bake for 12-15 minutes or until salmon flakes easily with a fork.',
      'Serve hot with your favorite side dish.',
    ],
    createdAt: new Date('2023-12-31T22:00:00Z'),
    modifiedAt: new Date('2024-01-01T00:00:00Z'),
  },
];

export type { RecipeRaw, Recipe, RecipeUpdate };
export { RECIPES, NEW_RECIPE_ID };
