type IngredientEntry = {
  amount: string;
  ingredient: string;
};
type Step = string;

type RecipeContent = {
  name: string;
  ingredients: IngredientEntry[];
  method: Step[];
};

type RecipeBase = RecipeContent & {
  id: string;
};

// Recipe sa parsed from AsyncStorage
type RecipeRaw = RecipeBase & {
  createdAt: string;
  modifiedAt: string;
};

type Recipe = RecipeBase & {
  createdAt: Date;
  modifiedAt: Date;
};

const NEW_RECIPE_ID = 'NEW RECIPE';

const RECIPES: Recipe[] = [
  {
    id: 'a',
    name: 'Pasta e Fagioli',
    ingredients: [
      {
        amount: '2 (15 oz) cans',
        ingredient: 'cannellini beans, drained and rinsed',
      },
      { amount: '4-5', ingredient: 'cloves garlic, minced' },
      { amount: '1/4 cup', ingredient: 'extra virgin olive oil' },
      { amount: '1/4 cup', ingredient: 'tomato paste' },
      { amount: '1/2 cup', ingredient: 'diced yellow onion' },
      { amount: '1', ingredient: 'carrot, finely diced' },
      { amount: '1', ingredient: 'celery stalk, finely diced' },
      { amount: '4 cups', ingredient: 'vegetable or chicken stock' },
      { amount: '1/2 lb', ingredient: 'ditalini pasta' },
      { amount: '1 tsp', ingredient: 'dried oregano' },
      { amount: '1/2 tsp', ingredient: 'red pepper flakes' },
      {
        amount: 'to taste',
        ingredient: 'salt and freshly ground black pepper',
      },
      { amount: 'for garnish', ingredient: 'freshly grated Parmesan cheese' },
      { amount: 'for garnish', ingredient: 'fresh parsley, chopped' },
    ],
    method: [
      'In a large pot, heat olive oil over medium heat. Add garlic and sauté until fragrant, about 30 seconds.',
      'Add onion, carrot, and celery. Cook until vegetables are softened, about 5-7 minutes.',
      'Stir in tomato paste and cook for 1 minute to deepen the flavor.',
      'Add oregano, red pepper flakes, and season with salt and pepper.',
      'Pour in the stock and bring to a simmer.',
      'Puree one can of beans with a bit of the cooking liquid until smooth, then add to the pot.',
      'Add the remaining whole beans and simmer for 20-25 minutes.',
      'Meanwhile, cook the ditalini pasta in a separate pot of salted boiling water until al dente.',
      'Drain the pasta and add it to the soup.',
      'Adjust seasoning if needed and serve hot, garnished with Parmesan cheese and fresh parsley.',
    ],
    createdAt: new Date('2023-01-01T10:00:00Z'),
    modifiedAt: new Date('2023-01-02T12:00:00Z'),
  },
  {
    id: 'b',
    name: 'Pad Kee Mao (Drunken Noodles)',
    ingredients: [
      { amount: '8 oz', ingredient: 'wide rice noodles' },
      { amount: '2 tbsp', ingredient: 'vegetable oil' },
      { amount: '4 cloves', ingredient: 'garlic, minced' },
      { amount: '2-3', ingredient: "bird's eye chilies, thinly sliced" },
      { amount: '1/2 cup', ingredient: 'yellow onion, sliced' },
      { amount: '1/2 cup', ingredient: 'red bell pepper, sliced' },
      { amount: '1/2 cup', ingredient: 'green bell pepper, sliced' },
      { amount: '1/2 cup', ingredient: 'broccoli florets' },
      { amount: '1/4 cup', ingredient: 'oyster sauce' },
      { amount: '2 tbsp', ingredient: 'soy sauce' },
      { amount: '1 tbsp', ingredient: 'fish sauce' },
      { amount: '1 tbsp', ingredient: 'brown sugar' },
      { amount: '1 tbsp', ingredient: 'dark soy sauce' },
      { amount: '1 cup', ingredient: 'Thai basil leaves, loosely packed' },
      { amount: '1/2 cup', ingredient: 'grape tomatoes, halved' },
      { amount: '2', ingredient: 'eggs, beaten' },
      { amount: 'for garnish', ingredient: 'lime wedges' },
    ],
    method: [
      'Soak rice noodles in warm water for 20-30 minutes until pliable but still firm. Drain and set aside.',
      'In a small bowl, mix together oyster sauce, soy sauce, fish sauce, brown sugar, and dark soy sauce. Set aside.',
      'Heat a wok or large skillet over high heat. Add 1 tbsp oil and swirl to coat.',
      'Add beaten eggs and scramble until just set. Remove and set aside.',
      'Add remaining oil to the wok. Add garlic and chilies, stir-fry for 30 seconds until fragrant.',
      'Add onions and bell peppers, stir-fry for 2 minutes until slightly softened.',
      'Add broccoli and tomatoes, stir-fry for another minute.',
      'Add the drained noodles and sauce mixture. Toss everything together until well combined.',
      'Return the scrambled eggs to the wok and add Thai basil leaves.',
      'Continue stir-frying for another 1-2 minutes until everything is heated through and the basil is wilted.',
      'Serve hot with lime wedges on the side.',
    ],
    createdAt: new Date('2023-02-01T09:00:00Z'),
    modifiedAt: new Date('2023-02-01T10:30:00Z'),
  },
  {
    id: 'c',
    name: "Penne all'Arrabbiata",
    ingredients: [
      { amount: '1 lb', ingredient: 'penne pasta' },
      { amount: '1/4 cup', ingredient: 'extra virgin olive oil' },
      { amount: '6 cloves', ingredient: 'garlic, thinly sliced' },
      { amount: '1 tsp', ingredient: 'red chili flakes (or to taste)' },
      {
        amount: '1 (28 oz) can',
        ingredient: 'San Marzano tomatoes, crushed by hand',
      },
      { amount: '1/4 cup', ingredient: 'dry white wine' },
      { amount: '1/2 cup', ingredient: 'fresh basil leaves, torn' },
      {
        amount: 'to taste',
        ingredient: 'sea salt and freshly ground black pepper',
      },
      {
        amount: 'for serving',
        ingredient: 'freshly grated Pecorino Romano cheese',
      },
      {
        amount: 'for serving',
        ingredient: 'extra virgin olive oil for drizzling',
      },
    ],
    method: [
      'Bring a large pot of salted water to boil for the pasta.',
      'In a large skillet, heat olive oil over medium heat. Add garlic and chili flakes, sauté until garlic is golden but not burned, about 2 minutes.',
      'Add the white wine and let it reduce by half, about 2 minutes.',
      'Add the crushed tomatoes and their juices. Season with salt and pepper.',
      'Simmer the sauce over medium-low heat for 20-25 minutes, stirring occasionally, until slightly thickened.',
      'Meanwhile, cook the penne in the boiling water until al dente (about 11-12 minutes).',
      'Reserve 1/2 cup of pasta water, then drain the pasta.',
      'Add the cooked pasta to the sauce along with the torn basil leaves.',
      'Toss everything together, adding pasta water as needed to create a silky sauce that coats the pasta.',
      'Serve immediately with grated Pecorino Romano and a drizzle of extra virgin olive oil.',
    ],
    createdAt: new Date('2023-03-01T08:00:00Z'),
    modifiedAt: new Date('2023-03-02T08:30:00Z'),
  },
  {
    id: 'd',
    name: 'Classic Margherita Pizza',
    ingredients: [
      { amount: '1 lb', ingredient: 'pizza dough (homemade or store-bought)' },
      { amount: '1/2 cup', ingredient: 'San Marzano tomato sauce' },
      {
        amount: '8 oz',
        ingredient: 'fresh mozzarella di bufala, sliced into 1/4-inch rounds',
      },
      { amount: '1/4 cup', ingredient: 'fresh basil leaves, torn' },
      { amount: '2 tbsp', ingredient: 'extra virgin olive oil' },
      { amount: '1/4 tsp', ingredient: 'dried oregano' },
      {
        amount: 'to taste',
        ingredient: 'sea salt and freshly ground black pepper',
      },
      { amount: 'for serving', ingredient: 'freshly grated Parmesan cheese' },
      { amount: 'for dusting', ingredient: 'semolina flour or cornmeal' },
    ],
    method: [
      'Preheat oven to 475°F (245°C) with a pizza stone or steel if available.',
      'On a lightly floured surface, roll out the pizza dough to a 12-inch circle.',
      'Transfer the dough to a pizza peel or baking sheet dusted with semolina flour.',
      'Spread the tomato sauce evenly over the dough, leaving a 1-inch border for the crust.',
      'Arrange the mozzarella slices evenly over the sauce.',
      'Drizzle with olive oil and sprinkle with oregano, salt, and pepper.',
      'Transfer the pizza to the preheated oven and bake for 10-12 minutes until the crust is golden and the cheese is bubbling.',
      'Remove from oven and immediately top with fresh basil leaves.',
      'Let rest for 1-2 minutes before slicing and serving with grated Parmesan on the side.',
    ],
    createdAt: new Date('2023-04-01T07:00:00Z'),
    modifiedAt: new Date('2023-04-01T09:00:00Z'),
  },
  {
    id: 'e',
    name: 'Chicken Tikka Masala',
    ingredients: [
      {
        amount: '2 lbs',
        ingredient: 'boneless, skinless chicken thighs, cut into 1-inch pieces',
      },
      { amount: '1 cup', ingredient: 'plain whole milk yogurt' },
      { amount: '2 tbsp', ingredient: 'fresh ginger, grated' },
      { amount: '4 cloves', ingredient: 'garlic, minced' },
      { amount: '2 tbsp', ingredient: 'garam masala' },
      { amount: '1 tsp', ingredient: 'ground turmeric' },
      { amount: '1 tsp', ingredient: 'ground cumin' },
      { amount: '1 tsp', ingredient: 'ground coriander' },
      { amount: '1/2 tsp', ingredient: 'cayenne pepper' },
      { amount: '2 tbsp', ingredient: 'vegetable oil' },
      { amount: '1 large', ingredient: 'yellow onion, finely diced' },
      { amount: '1 (28 oz) can', ingredient: 'crushed tomatoes' },
      { amount: '1 cup', ingredient: 'heavy cream' },
      { amount: '1/4 cup', ingredient: 'fresh cilantro, chopped' },
      {
        amount: 'to taste',
        ingredient: 'salt and freshly ground black pepper',
      },
      { amount: 'for serving', ingredient: 'basmati rice, cooked' },
      { amount: 'for serving', ingredient: 'naan bread' },
    ],
    method: [
      'In a large bowl, combine yogurt, ginger, garlic, 1 tbsp garam masala, turmeric, cumin, coriander, and cayenne pepper.',
      'Add chicken pieces and toss to coat. Cover and refrigerate for at least 2 hours, preferably overnight.',
      'Preheat oven to 400°F (200°C). Line a baking sheet with foil and place a wire rack on top.',
      'Remove chicken from marinade, shaking off excess, and arrange on the wire rack.',
      'Bake for 15-20 minutes until chicken is cooked through and slightly charred.',
      'Meanwhile, heat oil in a large skillet over medium heat. Add onions and cook until soft and golden, about 8-10 minutes.',
      'Add remaining 1 tbsp garam masala and cook for 1 minute until fragrant.',
      'Stir in crushed tomatoes and simmer for 10 minutes.',
      'Add heavy cream and cooked chicken. Simmer for another 5-10 minutes until sauce thickens slightly.',
      'Season with salt and pepper to taste.',
      'Garnish with fresh cilantro and serve hot with basmati rice and naan bread.',
    ],
    createdAt: new Date('2023-05-01T06:00:00Z'),
    modifiedAt: new Date('2023-05-01T07:30:00Z'),
  },
  {
    id: 'f',
    name: 'Shakshuka',
    ingredients: [
      { amount: '3 tbsp', ingredient: 'extra virgin olive oil' },
      { amount: '1 large', ingredient: 'yellow onion, diced' },
      { amount: '1 large', ingredient: 'red bell pepper, diced' },
      { amount: '1 large', ingredient: 'green bell pepper, diced' },
      { amount: '4 cloves', ingredient: 'garlic, minced' },
      { amount: '1 tsp', ingredient: 'ground cumin' },
      { amount: '1 tsp', ingredient: 'smoked paprika' },
      { amount: '1/2 tsp', ingredient: 'ground coriander' },
      { amount: '1/4 tsp', ingredient: 'cayenne pepper' },
      {
        amount: '1 (28 oz) can',
        ingredient: 'whole peeled tomatoes, crushed by hand',
      },
      { amount: '1 tbsp', ingredient: 'tomato paste' },
      { amount: '6', ingredient: 'large eggs' },
      { amount: '1/4 cup', ingredient: 'fresh parsley, chopped' },
      { amount: '1/4 cup', ingredient: 'fresh cilantro, chopped' },
      {
        amount: 'to taste',
        ingredient: 'salt and freshly ground black pepper',
      },
      { amount: 'for serving', ingredient: 'crusty bread or pita' },
      { amount: 'for serving', ingredient: 'feta cheese, crumbled' },
    ],
    method: [
      'Heat olive oil in a large, deep skillet over medium heat.',
      'Add onions and bell peppers. Cook, stirring occasionally, until vegetables are soft and onions are translucent, about 10 minutes.',
      'Add garlic and cook for 1 minute until fragrant.',
      'Stir in cumin, smoked paprika, coriander, and cayenne pepper. Cook for 1 minute to toast the spices.',
      'Add crushed tomatoes and their juices, along with tomato paste. Season with salt and pepper.',
      'Simmer the sauce for 15-20 minutes until slightly thickened.',
      'Using a spoon, create 6 small wells in the sauce. Crack an egg into each well.',
      'Cover the skillet and cook for 5-8 minutes until the egg whites are set but yolks are still runny.',
      'Remove from heat and sprinkle with fresh parsley and cilantro.',
      'Serve hot with crusty bread or pita and crumbled feta cheese on the side.',
    ],
    createdAt: new Date('2023-06-01T05:00:00Z'),
    modifiedAt: new Date('2023-06-01T06:00:00Z'),
  },
  {
    id: 'g',
    name: 'Classic Guacamole',
    ingredients: [
      { amount: '4', ingredient: 'ripe Hass avocados' },
      { amount: '1/4 cup', ingredient: 'red onion, finely diced' },
      { amount: '2', ingredient: 'Roma tomatoes, seeded and diced' },
      {
        amount: '1-2',
        ingredient: 'jalapeño peppers, seeded and finely diced',
      },
      { amount: '1/4 cup', ingredient: 'fresh cilantro, chopped' },
      { amount: '2 cloves', ingredient: 'garlic, minced' },
      { amount: '2', ingredient: 'limes, juiced' },
      { amount: '1/2 tsp', ingredient: 'ground cumin' },
      {
        amount: 'to taste',
        ingredient: 'sea salt and freshly ground black pepper',
      },
      { amount: 'for serving', ingredient: 'tortilla chips' },
      { amount: 'for serving', ingredient: 'lime wedges' },
    ],
    method: [
      'Cut the avocados in half, remove the pits, and scoop the flesh into a large bowl.',
      'Using a fork or potato masher, mash the avocados to your desired consistency (chunky or smooth).',
      'Add the diced red onion, tomatoes, jalapeño, cilantro, and minced garlic.',
      'Squeeze in the lime juice and sprinkle with cumin.',
      'Gently fold all ingredients together until well combined.',
      'Season with salt and pepper to taste.',
      'Cover with plastic wrap, pressing it directly onto the surface of the guacamole to prevent browning.',
      'Refrigerate for 30 minutes to allow flavors to meld.',
      'Serve with tortilla chips and lime wedges on the side.',
    ],
    createdAt: new Date('2023-07-01T04:00:00Z'),
    modifiedAt: new Date('2023-07-01T05:00:00Z'),
  },
  {
    id: 'h',
    name: 'Vegetable Stir-Fry',
    ingredients: [
      { amount: '2 tbsp', ingredient: 'peanut oil' },
      { amount: '1 tbsp', ingredient: 'sesame oil' },
      { amount: '1', ingredient: 'red bell pepper, sliced into strips' },
      { amount: '1', ingredient: 'yellow bell pepper, sliced into strips' },
      { amount: '1', ingredient: 'zucchini, sliced into half-moons' },
      { amount: '1', ingredient: 'yellow squash, sliced into half-moons' },
      { amount: '1 cup', ingredient: 'broccoli florets' },
      { amount: '1 cup', ingredient: 'snow peas, trimmed' },
      { amount: '1 cup', ingredient: 'baby corn, halved lengthwise' },
      { amount: '1 cup', ingredient: 'shiitake mushrooms, sliced' },
      { amount: '4 cloves', ingredient: 'garlic, minced' },
      { amount: '1 tbsp', ingredient: 'fresh ginger, grated' },
      { amount: '1/4 cup', ingredient: 'soy sauce' },
      { amount: '2 tbsp', ingredient: 'oyster sauce' },
      { amount: '1 tbsp', ingredient: 'rice vinegar' },
      { amount: '1 tbsp', ingredient: 'brown sugar' },
      { amount: '1 tsp', ingredient: 'cornstarch' },
      { amount: '2 tbsp', ingredient: 'water' },
      { amount: 'for garnish', ingredient: 'sesame seeds' },
      { amount: 'for garnish', ingredient: 'green onions, sliced' },
      { amount: 'for serving', ingredient: 'steamed jasmine rice' },
    ],
    method: [
      'In a small bowl, whisk together soy sauce, oyster sauce, rice vinegar, brown sugar, cornstarch, and water. Set aside.',
      'Heat a wok or large skillet over high heat. Add peanut oil and sesame oil.',
      'Add garlic and ginger, stir-fry for 30 seconds until fragrant.',
      'Add bell peppers, zucchini, and yellow squash. Stir-fry for 2-3 minutes.',
      'Add broccoli, snow peas, baby corn, and mushrooms. Continue stir-frying for another 2-3 minutes.',
      'Pour in the sauce mixture and toss to coat all vegetables evenly.',
      'Cook for another 1-2 minutes until the sauce thickens and vegetables are crisp-tender.',
      'Remove from heat and garnish with sesame seeds and green onions.',
      'Serve immediately over steamed jasmine rice.',
    ],
    createdAt: new Date('2023-08-01T03:00:00Z'),
    modifiedAt: new Date('2023-08-01T04:30:00Z'),
  },
  {
    id: 'i',
    name: 'Chocolate Chip Pancakes',
    ingredients: [
      { amount: '1 1/2 cups', ingredient: 'all-purpose flour' },
      { amount: '3 1/2 tsp', ingredient: 'baking powder' },
      { amount: '1 tsp', ingredient: 'baking soda' },
      { amount: '1/2 tsp', ingredient: 'salt' },
      { amount: '2 tbsp', ingredient: 'granulated sugar' },
      { amount: '1 1/4 cups', ingredient: 'buttermilk' },
      { amount: '1/2 cup', ingredient: 'whole milk' },
      { amount: '1', ingredient: 'large egg' },
      { amount: '3 tbsp', ingredient: 'unsalted butter, melted and cooled' },
      { amount: '1 tsp', ingredient: 'pure vanilla extract' },
      { amount: '3/4 cup', ingredient: 'semi-sweet chocolate chips' },
      { amount: 'for cooking', ingredient: 'butter or vegetable oil' },
      { amount: 'for serving', ingredient: 'maple syrup' },
      { amount: 'for serving', ingredient: 'whipped cream' },
      { amount: 'for serving', ingredient: 'fresh berries' },
    ],
    method: [
      'In a large bowl, whisk together flour, baking powder, baking soda, salt, and sugar.',
      'In a separate bowl, whisk together buttermilk, milk, egg, melted butter, and vanilla extract.',
      'Pour the wet ingredients into the dry ingredients and stir until just combined. Do not overmix.',
      'Gently fold in the chocolate chips.',
      'Heat a griddle or large non-stick skillet over medium heat. Lightly grease with butter or oil.',
      'Pour 1/4 cup of batter onto the griddle for each pancake.',
      'Cook until bubbles form on the surface and the edges look set, about 2-3 minutes.',
      'Flip and cook for another 1-2 minutes until golden brown.',
      'Keep cooked pancakes warm in a 200°F (95°C) oven while cooking the remaining batter.',
      'Serve hot with maple syrup, whipped cream, and fresh berries.',
    ],
    createdAt: new Date('2023-09-01T02:00:00Z'),
    modifiedAt: new Date('2023-09-01T03:00:00Z'),
  },
  {
    id: 'j',
    name: 'Classic Caprese Salad',
    ingredients: [
      {
        amount: '4',
        ingredient: 'large heirloom tomatoes, sliced 1/4-inch thick',
      },
      {
        amount: '8 oz',
        ingredient: 'fresh mozzarella di bufala, sliced 1/4-inch thick',
      },
      { amount: '1/2 cup', ingredient: 'fresh basil leaves, torn' },
      { amount: '1/4 cup', ingredient: 'extra virgin olive oil' },
      { amount: '2 tbsp', ingredient: 'aged balsamic vinegar' },
      { amount: '1/2 tsp', ingredient: 'flaky sea salt' },
      { amount: '1/4 tsp', ingredient: 'freshly ground black pepper' },
      { amount: 'for serving', ingredient: 'crusty bread' },
    ],
    method: [
      'Arrange alternating slices of tomato and mozzarella on a large serving platter.',
      'Tuck torn basil leaves between the slices.',
      'Drizzle with extra virgin olive oil and aged balsamic vinegar.',
      'Sprinkle with flaky sea salt and freshly ground black pepper.',
      'Let the salad sit at room temperature for 10-15 minutes to allow the flavors to meld.',
      'Serve with crusty bread on the side.',
    ],
    createdAt: new Date('2023-10-01T01:00:00Z'),
    modifiedAt: new Date('2023-10-01T02:00:00Z'),
  },
  {
    id: 'k',
    name: 'Garlic Butter Shrimp',
    ingredients: [
      {
        amount: '1 1/2 lbs',
        ingredient: 'large shrimp (16-20 count), peeled and deveined',
      },
      { amount: '3 tbsp', ingredient: 'unsalted butter' },
      { amount: '2 tbsp', ingredient: 'extra virgin olive oil' },
      { amount: '6 cloves', ingredient: 'garlic, minced' },
      { amount: '1/4 tsp', ingredient: 'red pepper flakes' },
      { amount: '1/4 cup', ingredient: 'dry white wine' },
      { amount: '2 tbsp', ingredient: 'fresh lemon juice' },
      { amount: '1/4 cup', ingredient: 'fresh parsley, chopped' },
      {
        amount: 'to taste',
        ingredient: 'sea salt and freshly ground black pepper',
      },
      { amount: 'for serving', ingredient: 'lemon wedges' },
      { amount: 'for serving', ingredient: 'crusty bread or cooked rice' },
    ],
    method: [
      'Pat the shrimp dry with paper towels and season with salt and pepper.',
      'In a large skillet, heat 1 tbsp butter and olive oil over medium-high heat.',
      'Add shrimp in a single layer and cook for 1-2 minutes per side until pink and opaque. Remove and set aside.',
      'Reduce heat to medium and add remaining butter to the skillet.',
      'Add garlic and red pepper flakes, sauté for 30 seconds until fragrant.',
      'Pour in white wine and lemon juice, scraping up any browned bits from the bottom of the pan.',
      'Simmer for 2-3 minutes until the sauce slightly reduces.',
      'Return the shrimp to the skillet and toss to coat with the sauce.',
      'Stir in chopped parsley and cook for another minute.',
      'Serve hot with lemon wedges and crusty bread or over rice.',
    ],
    createdAt: new Date('2023-11-01T00:00:00Z'),
    modifiedAt: new Date('2023-11-01T01:00:00Z'),
  },
  {
    id: 'l',
    name: 'Mango Lassi',
    ingredients: [
      {
        amount: '2 cups',
        ingredient: 'ripe mango chunks (about 2 large mangoes)',
      },
      { amount: '1 cup', ingredient: 'plain whole milk yogurt' },
      { amount: '1/2 cup', ingredient: 'whole milk' },
      { amount: '2 tbsp', ingredient: 'honey or sugar' },
      { amount: '1/4 tsp', ingredient: 'ground cardamom' },
      { amount: '1/4 tsp', ingredient: 'ground cinnamon' },
      { amount: '1 cup', ingredient: 'ice cubes' },
      { amount: 'for garnish', ingredient: 'mint leaves' },
      { amount: 'for garnish', ingredient: 'ground pistachios' },
    ],
    method: [
      'Peel and dice the mangoes, removing the pit.',
      'In a blender, combine mango chunks, yogurt, milk, honey, cardamom, and cinnamon.',
      'Blend until smooth and creamy.',
      'Add ice cubes and blend again until smooth and frothy.',
      'Taste and adjust sweetness if needed.',
      'Pour into chilled glasses and garnish with mint leaves and ground pistachios.',
      'Serve immediately.',
    ],
    createdAt: new Date('2023-12-01T23:00:00Z'),
    modifiedAt: new Date('2023-12-02T00:00:00Z'),
  },
  {
    id: 'm',
    name: 'Baked Salmon with Dill',
    ingredients: [
      { amount: '4 (6 oz)', ingredient: 'salmon fillets, skin-on' },
      { amount: '2 tbsp', ingredient: 'extra virgin olive oil' },
      { amount: '1', ingredient: 'lemon, thinly sliced' },
      { amount: '1/4 cup', ingredient: 'fresh dill, chopped' },
      { amount: '2 cloves', ingredient: 'garlic, minced' },
      { amount: '1 tsp', ingredient: 'lemon zest' },
      { amount: '1/2 tsp', ingredient: 'sea salt' },
      { amount: '1/4 tsp', ingredient: 'freshly ground black pepper' },
      { amount: 'for serving', ingredient: 'lemon wedges' },
      {
        amount: 'for serving',
        ingredient: 'steamed asparagus or roasted vegetables',
      },
    ],
    method: [
      'Preheat oven to 375°F (190°C). Line a baking sheet with parchment paper.',
      'Pat salmon fillets dry with paper towels and place them skin-side down on the prepared baking sheet.',
      'In a small bowl, mix together olive oil, minced garlic, lemon zest, salt, and pepper.',
      'Brush the salmon fillets with the olive oil mixture.',
      'Top each fillet with lemon slices and sprinkle with chopped dill.',
      'Bake for 12-15 minutes, or until the salmon flakes easily with a fork.',
      'Remove from oven and let rest for 2-3 minutes.',
      'Serve hot with lemon wedges and your choice of steamed asparagus or roasted vegetables.',
    ],
    createdAt: new Date('2023-12-31T22:00:00Z'),
    modifiedAt: new Date('2024-01-01T00:00:00Z'),
  },
];

export type { IngredientEntry, Step, RecipeContent, RecipeRaw, Recipe };
export { RECIPES, NEW_RECIPE_ID };
