name: EAS Update on PR merge to main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  eas-update:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run EAS Update
        run: npx eas update --branch main --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
